name: site

on: 
  push:
     branches:
      - master
  # workflow_run:
  #   workflows: ["build-deploy"] 
  #   types:
  #     - completed
jobs:
  
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["18"]
    name: gh-pages-publish
    steps:
      - uses: actions/checkout@v2
      - uses: FranzDiebold/github-env-vars-action@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: build
        env:
          BASE_URL: "https://${{env.CI_REPOSITORY_OWNER}}.github.io/${{env.CI_REPOSITORY_NAME}}/"
        run: |
          npm install
          npm run build
      - uses: peaceiris/actions-gh-pages@v3
        name: GitHub Pages Deploy
        with:
          publish_dir: "src/.vuepress/dist/"
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: feishu-bot-message
        if: always()
        uses: foxundermoon/feishu-action@v2
        with:
          url: ${{ secrets.FEISHU_BOT_WEBHOOK_URL }}
          msg_type: text
          content: |
            text: |
              🐳 构建状态 - ${{ job.status }}
              
              repository: https://github.com/${{ github.repository }}

              committer: https://github.com/${{ github.actor }}
              
              compare: ${{ github.event.compare }}

              job status: ${{ job.status }}

              website: https://${{env.CI_REPOSITORY_OWNER}}.github.io/${{env.CI_REPOSITORY_NAME}}/
